### ISSUE TITLE
Problem with Distributional RL version

### ISSUE THREAD

**Issue by SHITIANYU-hue** [xueguangl23/dec-hdrqn#2]
Hi,

According to my understanding, if using distributional RL, the code should go through these lines below:
https://github.com/lyu-xg/dec-hdrqn/blob/master/qnet.py#L71
https://github.com/lyu-xg/dec-hdrqn/blob/master/qnet.py#L152

However, I found that actually implicit_quant=0, self.distributional=False. So I think the current version is not using distributional RL.

 If I set these variables as true, then it will have this error:

2021-03-01 23:23:53.282336: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2196, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'GatherNd' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 393, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2200, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'GatherNd' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1576, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Indices and updates specified for empty output shape for 'gradients/GatherNd_grad/ScatterNd' (op: 'ScatterNd') with input shapes: [128,2], [128,0], [3] and with input tensors computed as partial shapes: input[2] = [?,5,0].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 117, in <module>
    main()
  File "main.py", line 113, in main
    train(parser.parse_args())
  File "main.py", line 90, in train
    params.dynamic_h, agent_args=P)
  File "/home/tianyushi/code/dec-hdrqn/team.py", line 32, in __init__
    for i in range(n_agent)
  File "/home/tianyushi/code/dec-hdrqn/team.py", line 32, in <listcomp>
    for i in range(n_agent)
  File "/home/tianyushi/code/dec-hdrqn/qnet.py", line 41, in __init__
    self.construct_training_method()
  File "/home/tianyushi/code/dec-hdrqn/qnet.py", line 164, in construct_training_method
    self.update_model = tf.train.AdamOptimizer(learning_rate=self.learning_rate).minimize(self.loss)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 400, in minimize
    grad_loss=grad_loss)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 514, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 398, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 489, in _GatherNdGrad
    ref_grad = array_ops.scatter_nd(indices, grad, ref_shape)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6788, in scatter_nd
    "ScatterNd", indices=indices, updates=updates, shape=shape, name=name)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1731, in __init__
    control_input_ops)
  File "/home/tianyushi/miniconda3/envs/hdrqn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Indices and updates specified for empty output shape for 'gradients/GatherNd_grad/ScatterNd' (op: 'ScatterNd') with input shapes: [128,2], [128,0], [3] and with input tensors computed as partial shapes: input[2] = [?,5,0].

**Comment by lyu-xg** [comment]
The distributional loss can only be activated through `n_quant` param, for example: 
```
python main.py --env capture_target --likely 1 --distort_type wang --n_quant 16
```
It determines how many quantile samples are taken.
